core/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('job_search.urls')),
]

job_search/urls.py
from django.urls import path
from . import views
from job_search.views import *

app_name = 'job_search'

urlpatterns = [
    path('', IndexView.as_view(), name='home'),
    path('about/', AboutView.as_view(), name='about'),
    path('links/', LinksView.as_view(), name='links'),
    path('blog/', BlogsView.as_view(), name='blog'),
    path('blog/<slug:slug>/', BlogView.as_view(), name='blog'),
    path('app/<int:pk>/', AppView.as_view(), name='app'),
    path('create/', CreateView.as_view(), name='create'),
    path('applied/', AppliedView.as_view(), name='applied'),
    path('active/', ActiveView.as_view(), name='active'),
    path('dead/', DeadView.as_view(), name='dead'),
]

job_search/models.py
from django.db import models


class PersonOfContact(models.Model):
    first_name = models.CharField(max_length=20)
    last_name = models.CharField(max_length=20)
    email = models.EmailField(max_length=60, null=True, blank=True)
    phone_number = models.CharField(max_length=12, null=True, blank=True)
    DORR = [
        ('Direct', 'Direct'),
        ('Recruiter', 'Recruiter')
    ]
    direct_or_recruiter = models.CharField(choices=DORR, max_length=20)

    def __str__(self):
        return f"{self.first_name} {self.last_name}"


class Company(models.Model):
    company_name = models.CharField(max_length=60)
    person_of_contact = models.ForeignKey(PersonOfContact, on_delete=models.CASCADE, null=True, blank=True)

    def __str__(self):
        return self.company_name


class ContactEvent(models.Model):
    company_name = models.ForeignKey(Company, on_delete=models.CASCADE, null=True, blank=True)
    event_date = models.DateField()
    person_of_contact = models.ForeignKey(PersonOfContact, on_delete=models.CASCADE)
    notes = models.TextField()

    def __str__(self):
        return f"{str(self.person_of_contact)} {self.event_date}"


class Application(models.Model):
    company_name = models.ForeignKey(Company, on_delete=models.CASCADE, null=True, blank=True)
    industry = models.CharField(max_length=60)
    role_title = models.CharField(max_length=60, null=True, blank=True)
    job_description = models.CharField(max_length=120, null=True, blank=True)
    date_applied = models.DateField()
    contact_events = models.ForeignKey(ContactEvent, on_delete=models.CASCADE, null=True, blank=True)
    person_of_contact = models.ForeignKey(PersonOfContact, on_delete=models.CASCADE, null=True, blank=True)
    STATUSES = [
        ('Applied', 'Applied'),
        ('Active', 'Active'),
        ('Dead', 'Dead')
    ]
    status = models.CharField(
        choices=STATUSES,
        max_length=10
    )

    def __str__(self):
        return str(self.company_name)


class Blog(models.Model):
    title = models.CharField(max_length=50)
    subtitle = models.CharField(max_length=50)
    date = models.DateField
    body = models.TextField()
    slug = models.SlugField(max_length=300)

    def __str__(self):
        return str(self.title)

job_search/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.views.generic import TemplateView, ListView, DetailView
from .models import *
from django.urls import reverse_lazy


class IndexView(TemplateView):
    template_name = "index.html"
    success_url = reverse_lazy('home')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["applied_count"] = (Application.objects.filter(status="Applied")).count()
        context["active_count"] = Application.objects.filter(status="Active").count()
        context["dead_count"] = Application.objects.filter(status="Dead").count()
        return context


class AppsView(ListView):
    model = Application
    template_name = "applications.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        return context


class AboutView(TemplateView):
    template_name = "about.html"
    success_url = reverse_lazy('about')


class LinksView(TemplateView):
    template_name = "links.html"
    success_url = reverse_lazy('links')


class AppView(DetailView):
    model = Application
    template_name = "application.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        return context
    

class BlogsView(ListView):
    model = Blog
    template_name = "blogs.html"
    success_url = reverse_lazy('blog')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        return context


class BlogView(DetailView):
    model = Blog
    template_name = "blog_detail.html"
    success_url = reverse_lazy('blog', slug= 'slug' )

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        return context
    

class AppliedView(ListView):
    model = Application
    template_name = "applied.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["applied"] = Application.objects.filter(status="Applied")
        return context


class ActiveView(ListView):
    model = Application
    template_name = "active.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["active"] = Application.objects.filter(status='Active')
        return context


class DeadView(ListView):
    model = Application
    template_name = "dead.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['dead'] = Application.objects.filter(status='Dead')
        return context


class CreateView(TemplateView):
    template_name = "add_view.html"

templates/about.html
{% extends "base.html" %}
{% block title %}Jacob's Job Search | About{% endblock %}
{% block content%}
<br>
<h3>This is the about page</h3>
{% endblock%}

templates/active.html
{% extends "base.html" %}
{% block title %}Jacob's Job Search | Active{% endblock %}
{% block content %}
<br>
<h3>This is the about page</h3>
    Active
    <br>
    {% for app in active %}
        {{app}}
    {% endfor %}
{% endblock %}

templates/add_view.html
{% extends "base.html" %}
{% block title %}Jacob's Job Search | Active{% endblock %}
{% block content%}
    Add view
{% endblock %}

templates/application.html
{% extends "base.html" %}
{% block title %}Jacob's Job Search | {{object}}{% endblock %}
{% block content %}
    This is the applications page for app {{object.id}}
{% endblock %}

templates/applied.html
{% extends "base.html" %}
{% block title %}Jacob's Job Search | Applied{% endblock %}
{% block content %}
    Applied
    {% for app in applied %}
        {{app}}
    {% endfor %}
{% endblock %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <link rel="stylesheet" href="{% static '/css/main.css' %}">
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% endblock %}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM" crossorigin="anonymous">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Inter:wght@100;200;400&display=swap" rel="stylesheet">
  </head>
<body>
    <nav class="navbar navbar-expand-lg bg-body-tertiary">
        <div class="container-fluid">
          <a class="navbar-brand" href="{% url 'job_search:home' %}">Jacob's Job Search</a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
              <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="{% url 'job_search:blog' %}">Blog</a>
              </li>
              <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="{% url 'job_search:about' %}">About</a>
              </li>
              <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="{% url 'job_search:links' %}">Links</a>
              </li>
            </ul>
          </div>
        </div>
      </nav>
    {% block content%}{% endblock %}
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-geWF76RCwLtnZ8qwWowPQNguL3RmwHVBC9FhGdlKrxdiJJigb/j/68SIy3Te4Bkz" crossorigin="anonymous"></script>
</body>
</html>

templates/blog_detail.html
{% extends "base.html" %}
{% block title %}Jacob's Job Search | {{object.title}}{% endblock %}
{% block content %}
    Page for blog # {{object.title}}
{% endblock %}

templates/blogs.html
{% extends "base.html" %}
{% block title %}Jacob's Job Search | Blog{% endblock %}
{% block content %}
    Blog List Page
    <ul>
        {% for blog in object_list %}
        <li>
            {{blog.title}}
            <a href="{% url 'job_search:blog' slug=blog.slug %}">Blog</a>
        </li>
        {% endfor %}
    </ul>
{% endblock %}

templates/dead.html
{% extends "base.html" %}
{% block title %}Jacob's Job Search | Dead{% endblock %}
{% block content %}
    Dead
    {% for app in dead %}
        {{app}}
    {% endfor %}
{% endblock %}

templates/index.html
{% extends "base.html" %}
{% block title %}Jacob's Job Search | Home{% endblock %}
{% block content %}
    <h1 class="index_header text-center">Jacob's Job Hunt</h1>
    <h2 class="index_subheader text-center">"something will shake loose..."</h2>
    <div class="container">
        <a class="link_style" href="{% url 'job_search:blog' %}">
            <div class="item count_box">
                <h3 class="box_font_text">Applied</h3>
                <div class="text-center box_font_numbers">{{applied_count}}</div>
            </div>
        </a>
        <a class="link_style" href="{% url 'job_search:blog' %}">
            <div class="item count_box">
                <h3 class="box_font_text">Active</h3>
                <div class="text-center box_font_numbers">{{active_count}}</div>
            </div>
        </a>
        <a class="link_style" href="{% url 'job_search:blog' %}">
            <div class="item count_box">
                <h3 class="box_font_text">Dead</h3>
                <div class="text-center box_font_numbers">{{dead_count}}</div>
            </div>
        </a>
    </div>
    <h5 class="body_text_sub">Follow me on my journey to my next software role</h5>
    <p class="body_text">As of May 2023, I found myself looking for a new role. My most recent position was as a Data Engineer, but as you might have noticed from this nifty website, I have a background in web developement as well.</p>
    <p class="body_text"> For a full discussion of my background, skill set, and work experience, check out the <a class='link_style_bold' href="{% url 'job_search:about' %}">About</a> page for all the details.</p>
    <p class="body_text">Also, check out my <a class='link_style_bold' href="{% url 'job_search:blog' %}">Blog</a> as I chronical the challenges and insights of the horrible slog that is looking for a new gig. It might even be useful to others who find themselves stuck in this lame situation.</p>
{% endblock %}

templates/links.html
{% extends "base.html" %}
{% block title %}Jacob's Job Search | Links and Contact{% endblock %}
{% block content %}
Links and Contact
{% endblock%}